site_name: Migaga
repo_url: https://github.com/LewisHobden/Migaga
repo_name: Migaga
site_description: Welcome to the Migaga docs, here you can find some instructions on making use of the bot.
theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep-purple
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: images/logo.png
  favicon: images/favicon.png

edit_uri: ""

nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'Configuration':
      - 'Config Commands': 'configuration/config-commands.md'
      - 'Role Overrides': 'configuration/role-overrides.md'
  - 'Features':
      - 'Booster Roles': 'features/booster-roles/index.md'
      - 'Reaction Flairs': 'features/reaction-flairs/index.md'
      - 'Logging': 'features/server-logs/index.md'
      - 'Message Events': 'features/message-events/index.md'
      - 'Points': 'features/points/index.md'
      - 'Starboard': 'features/starboard/index.md'
      - 'Welcome Messages': 'features/welcome-message/index.md'
#      - 'Miscellaneous': 'features/misc.md'
#  - 'Development': 'setup.md'
#  - 'Privacy': 'privacy.md'
  - 'Donations': https://ko-fi.com/backslashlewis
  - 'Join our server': https://server.migaga.info/
  - 'Invite the bot': https://invite.migaga.info/